loop:
  gain: 0.0001
  numDroppedModes: 30
  pokeAmp: 0.02
  numItersIM: 50
  affinity: 2
  delay: 2
  method: push-pull
  IMFile: "/home/whetstone/pyRTC/SHARP_LAB/IM.npy"
  AImodel: "shlong_10_default0m_SAM"
  AIhalfPrecision: False
  AIdevice: "cuda:0"
  AIburnIn: 50000
  AIresidualLength: 250000
  functions:
  # - standardIntegrator
  - standardIntegratorPOL


wfs:
  name: XIMEA
  serial: "46052550"
  binning: 2
  exposure: 2000
  gain: 0
  bitDepth: 10
  left: 208
  top: 140
  width: 192
  height: 192
  darkCount: 1000
  darkFile: "/home/whetstone/pyRTC/SHARP_LAB/dark.npy"
  affinity: 3
  functions:
  - expose

slopes:
  type: SHWFS
  signalType: slopes
  refSlopesFile: "/home/whetstone/pyRTC/SHARP_LAB/ref.npy"
  validSubApsFile: "/home/whetstone/pyRTC/SHARP_LAB/validSubAps.npy"
  subApSpacing: 7.8
  subApOffsetX: 3
  subApOffsetY: 3
  affinity: 4
  functions:
  - computeSignal

# wfs:
#   name: XIMEA
#   serial: "13056250"
#   type: PYWFS
#   signalType: slopes
#   pupilsRadius: 32
#   binning: 2
#   exposure: 3333
#   gain: 0
#   bitDepth: 10
#   left: 272
#   top: 50
#   width: 192
#   height: 192
#   darkCount: 1000
#   darkFile: "/home/whetstone/pyRTC/SHARP_LAB/dark.npy"
#   affinity: 12
#   flatNorm: True
#   pupils: 
#   - 44,57
#   - 45,138
#   - 150,75
#   - 130,138
#   functions:
#   - expose
#   - computeSignal

wfc:
  name: "ALPAO"
  serial: "BAX118"
  numActuators: 97
  numModes: 95
  flatFile: "/home/whetstone/pyRTC/SHARP_LAB/wfcShape.npy"
  saveFile: "/home/whetstone/pyRTC/SHARP_LAB/wfcShape.npy"
  m2cFile:  "/home/whetstone/m2c_zern_manual.npy" #"/etc/chai/m2c_kl.dat"
  affinity: 5
  commandCap: 0.8
  hardwareDelay: 0.001 #seconds
  frameDelay: 0
  functions:
  - sendToHardware

psf:
  name: "FLIR"
  index: 0
  exposure: 80
  gain: 0
  bitDepth: 16
  left: 808
  top: 420
  width: 128
  height: 128
  darkCount: 1000
  darkFile: "/home/whetstone/pyRTC/SHARP_LAB/psfDark.npy"
  integration: 500000
  affinity: 6
  functions:
  - expose
  - integrate

modulator:
  name: 'E-727'
  libFolder: '/opt/PI/lib64/'
  digitalFreq: 20000 #Hz
  frequency: 300 #Hz
  amplitude: 1000
  relativeAmplitude: 1
  offsetX: 2500
  offsetY: 2500
  phaseOffset: 0
  servosOn: True
  autoZero: True

